# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/part2/project_sol2/project_sol2.srcs/sources_1/bd/design_proj2/ip/design_proj2_xbar_1/design_proj2_xbar_1.xci
# IP: The module: 'design_proj2_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/part2/project_sol2/project_sol2.srcs/sources_1/bd/design_proj2/ip/design_proj2_xbar_1/design_proj2_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_proj2_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/part2/project_sol2/project_sol2.srcs/sources_1/bd/design_proj2/ip/design_proj2_xbar_1/design_proj2_xbar_1.xci
# IP: The module: 'design_proj2_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/part2/project_sol2/project_sol2.srcs/sources_1/bd/design_proj2/ip/design_proj2_xbar_1/design_proj2_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_proj2_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
