# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Temp/code_de_depart_partie2/projet_sol3_3/projet_sol3_3.srcs/sources_1/bd/design_1/ip/design_1_HLS_accel_0_0_1/design_1_HLS_accel_0_0.xci
# IP: The module: 'design_1_HLS_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Temp/code_de_depart_partie2/projet_sol3_3/projet_sol3_3.srcs/sources_1/bd/design_1/ip/design_1_HLS_accel_0_0_1/constraints/HLS_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_HLS_accel_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Temp/code_de_depart_partie2/projet_sol3_3/projet_sol3_3.srcs/sources_1/bd/design_1/ip/design_1_HLS_accel_0_0_1/design_1_HLS_accel_0_0.xci
# IP: The module: 'design_1_HLS_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Temp/code_de_depart_partie2/projet_sol3_3/projet_sol3_3.srcs/sources_1/bd/design_1/ip/design_1_HLS_accel_0_0_1/constraints/HLS_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_HLS_accel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
