# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_proj2/design_proj2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2 || ORIG_REF_NAME==design_proj2} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_HLS_accel_1_0/design_proj2_HLS_accel_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_HLS_accel_1_0 || ORIG_REF_NAME==design_proj2_HLS_accel_1_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_axi_dma_1_0/design_proj2_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_axi_dma_1_0 || ORIG_REF_NAME==design_proj2_axi_dma_1_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_xbar_0/design_proj2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_xbar_0 || ORIG_REF_NAME==design_proj2_xbar_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_auto_us_0/design_proj2_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_auto_us_0 || ORIG_REF_NAME==design_proj2_auto_us_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_auto_us_1/design_proj2_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_auto_us_1 || ORIG_REF_NAME==design_proj2_auto_us_1} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_auto_pc_0/design_proj2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_auto_pc_0 || ORIG_REF_NAME==design_proj2_auto_pc_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_axi_interconnect_0_0/design_proj2_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_axi_interconnect_0_0 || ORIG_REF_NAME==design_proj2_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_xbar_1/design_proj2_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_xbar_1 || ORIG_REF_NAME==design_proj2_xbar_1} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_auto_pc_1/design_proj2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_auto_pc_1 || ORIG_REF_NAME==design_proj2_auto_pc_1} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_axi_interconnect_1_0/design_proj2_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_axi_interconnect_1_0 || ORIG_REF_NAME==design_proj2_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_axi_timer_1_0/design_proj2_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_axi_timer_1_0 || ORIG_REF_NAME==design_proj2_axi_timer_1_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_proc_sys_reset_0/design_proj2_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_proc_sys_reset_0 || ORIG_REF_NAME==design_proj2_proc_sys_reset_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_processing_system7_0_0/design_proj2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_processing_system7_0_0 || ORIG_REF_NAME==design_proj2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_proj2/ip/design_proj2_xlconcat_1_0/design_proj2_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proj2_xlconcat_1_0 || ORIG_REF_NAME==design_proj2_xlconcat_1_0} -quiet] -quiet

# XDC: bd/design_proj2/design_proj2_ooc.xdc
