# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_0/design_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0 || ORIG_REF_NAME==design_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_HLS_accel_0_1/design_0_HLS_accel_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_HLS_accel_0_1 || ORIG_REF_NAME==design_0_HLS_accel_0_1} -quiet] -quiet

# IP: bd/design_0/ip/design_0_HLS_accel_1_0/design_0_HLS_accel_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_HLS_accel_1_0 || ORIG_REF_NAME==design_0_HLS_accel_1_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_axi_dma_1_0/design_0_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_axi_dma_1_0 || ORIG_REF_NAME==design_0_axi_dma_1_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_axi_dma_2_0/design_0_axi_dma_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_axi_dma_2_0 || ORIG_REF_NAME==design_0_axi_dma_2_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_xbar_0/design_0_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_xbar_0 || ORIG_REF_NAME==design_0_xbar_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_auto_us_0/design_0_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_auto_us_0 || ORIG_REF_NAME==design_0_auto_us_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_auto_us_1/design_0_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_auto_us_1 || ORIG_REF_NAME==design_0_auto_us_1} -quiet] -quiet

# IP: bd/design_0/ip/design_0_auto_pc_0/design_0_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_auto_pc_0 || ORIG_REF_NAME==design_0_auto_pc_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_axi_interconnect_0_0/design_0_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_axi_interconnect_0_0 || ORIG_REF_NAME==design_0_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_xbar_1/design_0_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_xbar_1 || ORIG_REF_NAME==design_0_xbar_1} -quiet] -quiet

# IP: bd/design_0/ip/design_0_auto_pc_1/design_0_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_auto_pc_1 || ORIG_REF_NAME==design_0_auto_pc_1} -quiet] -quiet

# IP: bd/design_0/ip/design_0_axi_interconnect_1_0/design_0_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_axi_interconnect_1_0 || ORIG_REF_NAME==design_0_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_xbar_2/design_0_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_xbar_2 || ORIG_REF_NAME==design_0_xbar_2} -quiet] -quiet

# IP: bd/design_0/ip/design_0_auto_us_2/design_0_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_auto_us_2 || ORIG_REF_NAME==design_0_auto_us_2} -quiet] -quiet

# IP: bd/design_0/ip/design_0_auto_us_3/design_0_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_auto_us_3 || ORIG_REF_NAME==design_0_auto_us_3} -quiet] -quiet

# IP: bd/design_0/ip/design_0_auto_pc_2/design_0_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_auto_pc_2 || ORIG_REF_NAME==design_0_auto_pc_2} -quiet] -quiet

# IP: bd/design_0/ip/design_0_axi_interconnect_2_0/design_0_axi_interconnect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_axi_interconnect_2_0 || ORIG_REF_NAME==design_0_axi_interconnect_2_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_axi_timer_1_0/design_0_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_axi_timer_1_0 || ORIG_REF_NAME==design_0_axi_timer_1_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_axi_timer_2_0/design_0_axi_timer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_axi_timer_2_0 || ORIG_REF_NAME==design_0_axi_timer_2_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_proc_sys_reset_0/design_0_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_proc_sys_reset_0 || ORIG_REF_NAME==design_0_proc_sys_reset_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_processing_system7_0_0/design_0_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_processing_system7_0_0 || ORIG_REF_NAME==design_0_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_0/ip/design_0_xlconcat_1_0/design_0_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_0_xlconcat_1_0 || ORIG_REF_NAME==design_0_xlconcat_1_0} -quiet] -quiet

# XDC: bd/design_0/design_0_ooc.xdc
